kind: pipeline
type: docker
name: default

steps:
  - name: install
    image: node:14.17
    commands:
      - npm ci

  - name: lint
    image: node:14.17
    commands:
      - npx next lint

  - name: version
    image: node:14.17
    commands:
      - node ./version.js > .tags
      - cat .tags

  - name: build
    image: plugins/docker:20.10
    environment:
      SENTRY_AUTH_TOKEN:
        from_secret: SENTRY_AUTH_TOKEN
    settings:
      repo: cr.yandex/crptsm0vtuj4fltqor20/frontend
      registry: cr.yandex
      username: json_key
      password:
        from_secret: YC_IAM_SERVICE_ACCOUNT_AUTH_KEYS
      build_args_from_env:
        - SENTRY_AUTH_TOKEN
