language: node_js
before_install:
  - npm i -g npm@5
  - npm i -g greenkeeper-lockfile@1
before_script:
  - greenkeeper-lockfile-update
  - npm run lint:js
script:
  - npm run build
after_script:
  - greenkeeper-lockfile-upload