language: node_js
cache:
  yarn: true
before_script:
  - yarn run lint:js
script:
  - yarn run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master